### ISSUE TITLE
Some issues on BRI version 

### ISSUE THREAD

**Issue by hsxndfx** [LucasBlackLu/android_kernel_samsung_sm8350-common#2]
My phone is a Samsung S21 G9910, and the baseband version is G9910ZCS7FXBC. The original kernel version was 5.4.233. I used Kernel Flasher to flash a new kernel, and now the touch functionality on my phone doesn't work, and I can't use it normally. I tried flashing the recovery.img you released, but it failed to load the data partition.

**Comment by LucasBlackLu** [comment]
Did you flash Canary tag, it's work in progress, you should flash lavender tag

**Comment by LucasBlackLu** [comment]
Also to use the twrp I built ,
You need flash recovery.tar and disabler.tar then reboot to twrp,type multidisabler in terminal and wipe your data

**Comment by hsxndfx** [comment]
Thanks, TWRP worked and kernel flashed successful
