### ISSUE TITLE
After version Lavender-CI_8733061855

### ISSUE THREAD

**Issue by ucxl** [LucasBlackLu/android_kernel_samsung_sm8350-common#3]
After version Lavender-CI_8733061855, none of the versions can boot up. Is it possible to integrate Walt scheduling? Thank you.

**Comment by LucasBlackLu** [comment]
Because the version after Lavender-CI_8733061855 merge new tag, I hadn't fixed at that point so do I now, I'm working on the los working; I would add in the future thank you so much
